"""Module 8B: BCH (15,7) Code Identification, Alignment, and Decoding.

Implements:
1. BCH (15,7) Parameters:
   - n = 15, k = 7, t = 2.
   - Generator polynomial: g(x) = x^8 + x^7 + x^6 + x^4 + 1
     Binary representation: [1, 1, 1, 0, 1, 0, 0, 0, 1] (degree 8).
   - Codebook: 128 codewords x 15 bits generated by c(x) = m(x) * g(x) (mod 2).
   - Minimum Hamming distance = 5 (t=2 error correction).

2. Syndrome Consistency & Normalized Lift:
   - Syndrome: polynomial remainder s(x) = r(x) mod g(x) over GF(2).
   - Valid codewords yield s(x) = 0.
   - Random baseline: P_rand = 2^(-8) = 1/256 ≈ 0.00390625.
   - Normalized Lift: Lift_BCH = P(zero remainder) / P_rand.

3. Alignment Search:
   - Evaluates cyclic offsets tau in {0, 1, ..., 14}.
   - Selected offset maximizes zero-remainder fraction.

4. Decoders:
   - Hard Decoder: Nearest-codeword search (minimum Hamming distance over 128 codewords).
   - Soft ML Decoder: Evaluates soft correlation across all 128 codewords:
       c_hat = argmax_{c in C_BCH} sum_{j=0}^{14} s(c_j) * Lambda_j
     where s(1) = +1, s(0) = -1.

Status: LOCKED.
"""

from typing import Any, Dict, List, Optional, Tuple
import numpy as np


# Exact generator polynomial coefficients: g(x) = x^8 + x^7 + x^6 + x^4 + 1
# Represented in ascending power of x: index i corresponds to x^i
BCH_G_POLY = np.array([1, 0, 0, 0, 1, 0, 1, 1, 1], dtype=np.uint8)  # length 9, degree 8


def _poly_mult_gf2(p1: np.ndarray, p2: np.ndarray) -> np.ndarray:
    """Multiply two polynomials over GF(2)."""
    res = np.zeros(len(p1) + len(p2) - 1, dtype=np.uint8)
    for i, c1 in enumerate(p1):
        if c1:
            for j, c2 in enumerate(p2):
                if c2:
                    res[i + j] ^= 1
    return res


def _poly_div_gf2(dividend: np.ndarray, divisor: np.ndarray) -> np.ndarray:
    """Compute polynomial remainder dividend mod divisor over GF(2)."""
    rem = np.copy(dividend).astype(np.uint8)
    deg_div = len(divisor) - 1
    for i in range(len(rem) - 1, deg_div - 1, -1):
        if rem[i]:
            rem[i - deg_div : i + 1] ^= divisor
    return rem[:deg_div]


def _build_bch_codebook() -> Tuple[np.ndarray, np.ndarray, Dict[Tuple[int, ...], int]]:
    """Build precomputed codebook of 128 codewords and message mapping."""
    messages = np.array([
        [(i >> b) & 1 for b in range(7)] for i in range(128)
    ], dtype=np.uint8)

    codewords = np.zeros((128, 15), dtype=np.uint8)
    for i in range(128):
        c = _poly_mult_gf2(messages[i], BCH_G_POLY)
        codewords[i, :len(c)] = c

    cw_to_msg_idx: Dict[Tuple[int, ...], int] = {}
    for idx, cw in enumerate(codewords):
        cw_to_msg_idx[tuple(int(b) for b in cw)] = idx

    return messages, codewords, cw_to_msg_idx


# Precomputed codebook structures
BCH_MESSAGES, BCH_CODEWORDS, BCH_CW_TO_MSG_IDX = _build_bch_codebook()


def encode_bch_15_7(messages: np.ndarray) -> np.ndarray:
    """Encode an array of 7-bit messages into 15-bit BCH codewords.

    Args:
        messages: 1D or 2D binary array of messages (length must be multiple of 7).

    Returns:
        Flattened 1D binary array of codewords.
    """
    m = np.asarray(messages, dtype=np.uint8).flatten()
    n_blocks = len(m) // 7
    if n_blocks == 0:
        return np.array([], dtype=np.uint8)

    out = []
    for b_idx in range(n_blocks):
        m_blk = m[b_idx * 7 : (b_idx + 1) * 7]
        # Convert message bits to integer index 0..127
        idx = int(sum((int(m_blk[b]) << b) for b in range(7)))
        out.append(BCH_CODEWORDS[idx])

    return np.array(out, dtype=np.uint8).flatten()


def compute_bch_syndromes(bits: np.ndarray) -> Tuple[np.ndarray, float]:
    """Compute polynomial remainder syndromes for contiguous 15-bit blocks.

    Args:
        bits: 1D array of hard bits.

    Returns:
        Tuple of (syndromes array [N, 8], zero_syndrome_fraction).
    """
    n_blocks = len(bits) // 15
    if n_blocks == 0:
        return np.zeros((0, 8), dtype=np.uint8), 0.0

    blocks = bits[:n_blocks * 15].reshape(n_blocks, 15)
    zero_count = 0
    syndromes = []

    for blk in blocks:
        rem = _poly_div_gf2(blk, BCH_G_POLY)
        syndromes.append(rem)
        if np.sum(rem) == 0:
            zero_count += 1

    zero_fraction = float(zero_count / n_blocks)
    return np.array(syndromes, dtype=np.uint8), zero_fraction


def find_bch_alignment(bits: np.ndarray) -> Tuple[int, float, Dict[int, float]]:
    """Search for optimal BCH codeword alignment tau in {0, 1, ..., 14}.

    Args:
        bits: 1D array of received bits.

    Returns:
        Tuple of (best_offset, best_zero_fraction, dict_of_all_offsets).
    """
    best_offset = 0
    best_frac = -1.0
    all_offsets: Dict[int, float] = {}

    for offset in range(15):
        sub_bits = bits[offset:]
        _, frac = compute_bch_syndromes(sub_bits)
        all_offsets[offset] = frac
        if frac > best_frac:
            best_frac = frac
            best_offset = offset

    return best_offset, best_frac, all_offsets


def compute_bch_evidence(
    bits: np.ndarray,
    alignment_offset: Optional[int] = None
) -> Dict[str, Any]:
    """Compute normalized BCH evidence (lift) and syndrome statistics.

    Args:
        bits: 1D array of hard bits.
        alignment_offset: Optional known/forced offset. If None, alignment is searched.

    Returns:
        Dictionary containing zero_fraction, normalized_lift, and alignment.
    """
    if alignment_offset is None:
        best_offset, zero_frac, all_offsets = find_bch_alignment(bits)
    else:
        best_offset = alignment_offset
        _, zero_frac = compute_bch_syndromes(bits[best_offset:])
        all_offsets = {best_offset: zero_frac}

    random_baseline = 1.0 / 256.0  # 2^(-8)
    raw_lift = float(zero_frac / random_baseline) if random_baseline > 0 else 0.0
    normalized_lift = float(max(0.0, (zero_frac - random_baseline) / (1.0 - random_baseline)))

    return {
        "family": "BCH",
        "code": "BCH_15_7",
        "n": 15,
        "k": 7,
        "alignment_offset": best_offset,
        "zero_syndrome_fraction": zero_frac,
        "random_baseline": random_baseline,
        "raw_lift": raw_lift,
        "normalized_lift": normalized_lift,
        "all_offsets": all_offsets
    }


def decode_bch_hard(bits: np.ndarray) -> Tuple[np.ndarray, Dict[str, Any]]:
    """Perform hard minimum Hamming distance decoding over the 128 codewords.

    Args:
        bits: 1D array of received hard bits (must be aligned to block boundary).

    Returns:
        Tuple of (decoded_information_bits, decoding_metadata).
    """
    n_blocks = len(bits) // 15
    if n_blocks == 0:
        return np.array([], dtype=np.uint8), {"blocks": 0, "decoder_type": "BCH_HARD"}

    blocks = bits[:n_blocks * 15].reshape(n_blocks, 15)

    # Compute Hamming distances against all 128 codewords: shape (n_blocks, 128)
    # d_H(r, c) = sum(r != c)
    # Using matrix math: r (n_blocks, 15) vs BCH_CODEWORDS (128, 15)
    r_expanded = blocks[:, None, :]  # (N, 1, 15)
    cw_expanded = BCH_CODEWORDS[None, :, :]  # (1, 128, 15)
    diffs = np.sum(r_expanded != cw_expanded, axis=2)  # (N, 128)

    best_cw_indices = np.argmin(diffs, axis=1)
    best_messages = BCH_MESSAGES[best_cw_indices]

    return best_messages.flatten(), {
        "blocks": n_blocks,
        "mean_min_distance": float(np.mean(np.min(diffs, axis=1))),
        "decoder_type": "BCH_HARD"
    }


def decode_bch_soft_ml(soft_bits: np.ndarray) -> Tuple[np.ndarray, Dict[str, Any]]:
    """Perform soft Maximum-Likelihood (ML) decoding over all 128 candidate codewords.

    Evaluates:
        c_hat = argmax_{c in C_BCH} sum_{j=0}^{14} s(c_j) * Lambda_j
    where s(1) = +1, s(0) = -1.

    Args:
        soft_bits: 1D array of signed soft values / LLRs from Module 7.

    Returns:
        Tuple of (decoded_information_bits, decoding_metadata).
    """
    n_blocks = len(soft_bits) // 15
    if n_blocks == 0:
        return np.array([], dtype=np.uint8), {"blocks": 0, "decoder_type": "BCH_SOFT_ML"}

    soft_matrix = soft_bits[:n_blocks * 15].reshape(n_blocks, 15)

    # Polar mapping for all 128 codewords: 1 -> +1.0, 0 -> -1.0
    cw_polar = np.where(BCH_CODEWORDS == 1, 1.0, -1.0)  # shape (128, 15)

    # Correlation scores: shape (n_blocks, 128)
    scores = soft_matrix @ cw_polar.T

    best_cw_indices = np.argmax(scores, axis=1)
    best_messages = BCH_MESSAGES[best_cw_indices]

    return best_messages.flatten(), {
        "blocks": n_blocks,
        "mean_ml_score": float(np.mean(np.max(scores, axis=1))),
        "decoder_type": "BCH_SOFT_ML"
    }
